# See the slurm.conf man page for more information.
#
ClusterName=own4Cluster
SlurmctldHost=own4(10.100.0.4)
#
AuthType = auth/munge
AuthAltTypes=auth/jwt
AuthAltParameters=max_token_lifespan=604800,jwt_key=/var/spool/slurm/statesave/jwt_hs256.key
ProctrackType=proctrack/cgroup
ReturnToService=2
SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmctldPort=6817
SlurmdPidFile=/var/run/slurm/slurmd.pid
SlurmdPort=6818
SlurmdSpoolDir=/var/spool/slurmd
SlurmUser=slurm
StateSaveLocation=/var/spool/slurmctld
SwitchType=switch/none
TaskPlugin=task/cgroup,task/affinity
#
#
LaunchParameters=disable_send_gids
# TIMERS
InactiveLimit=0
KillWait=30
MinJobAge=300
SlurmctldTimeout=120
SlurmdTimeout=300
Waittime=0
#
# ACCT
AccountingStorageEnforce=associations,limits,qos
AccountingStorageTRES=gres/gpu,gres/shard
AccountingStorageType=accounting_storage/slurmdbd
JobAcctGatherType=jobacct_gather/cgroup
#
# SCHEDULING
SchedulerType=sched/backfill
SchedulerParameters=bf_continue,bf_interval=30,bf_window=1440,bf_resolution=300
SelectType=select/cons_tres
SelectTypeParameters=CR_CPU_Memory
DefMemPerCPU=1000
MaxMemPerCPU=4000
JobSubmitPlugins=lua
#
# Priority
PriorityType=priority/multifactor
PriorityWeightFairshare=100000
PriorityWeightAge=1000
PriorityWeightJobSize=100
PriorityWeightPartition=100
PriorityDecayHalfLife=1-0
#
# Logs
SlurmctldDebug=debug
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=debug2
SlurmdLogFile=/var/log/slurm/slurmd.log
#DebugFlags=Network
#
# Node options
SlurmdParameters=allow_ecores,config_overrides
#
# GPU
GresTypes=gpu,shard
#
# COMPUTE NODES
PartitionName=pzero Nodes=ALL Default=YES DefaultTime=1-0 MaxTime=INFINITE State=UP OverSubscribe=YES:2
PartitionName=pgpu Nodes=own[3-10] DefaultTime=1-0 MaxTime=INFINITE State=UP OverSubscribe=YES:2
PartitionName=pcpu Nodes=own[9-10] DefaultTime=1-0 MaxTime=INFINITE State=UP OverSubscribe=YES:2

# Boards, Sockets optoins not provided for own4 & own5 because of mismatch between "lscpu" and "slurmd -C"
# hence don't add them here (check intel processor's design on P-Cores and E-Cores to know more)
NodeName=own3 NodeAddr=10.100.0.2 CPUs=8 Boards=1 SocketsPerBoard=1 CoresPerSocket=4 ThreadsPerCore=2 RealMemory=62000 Gres=gpu:nvidia_geforce_gtx_1080_ti:1,shard:3580 State=UNKNOWN
NodeName=own4 NodeAddr=10.100.0.4 CPUs=32 RealMemory=124000 Gres=gpu:nvidia_geforce_rtx_4090:1,shard:16374 State=UNKNOWN
NodeName=own5 NodeAddr=10.100.0.5 CPUs=32 RealMemory=124000 Gres=gpu:nvidia_geforce_rtx_4090:1,shard:16374 State=UNKNOWN
NodeName=own6 NodeAddr=10.100.0.6 CPUs=32 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=2 RealMemory=124000 Gres=gpu:nvidia_geforce_rtx_4090:1,shard:16374 State=UNKNOWN
NodeName=own7 NodeAddr=10.100.0.7 CPUs=32 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=2 RealMemory=122880 Gres=gpu:nvidia_geforce_rtx_5080:1,shard:10742 State=UNKNOWN
NodeName=own8 NodeAddr=10.100.0.8 CPUs=32 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=2 RealMemory=122880 Gres=gpu:nvidia_geforce_rtx_5080:1,shard:10742 State=UNKNOWN
NodeName=own9 NodeAddr=10.100.0.9 CPUs=32 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=2 RealMemory=122880 Gres=gpu:nvidia_geforce_rtx_5080:1,shard:10742 State=UNKNOWN
NodeName=own10 NodeAddr=10.100.0.10 CPUs=32 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=2 RealMemory=122880 Gres=gpu:nvidia_geforce_rtx_5080:1,shard:10742 State=UNKNOWN

AccountingStorageHost=10.100.0.4
